# Generated by Django 3.1.2 on 2020-10-01 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NoticeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('deadline', models.PositiveIntegerField(default=0)),
                ('deadline_working_days', models.BooleanField(default=False)),
                ('deadline_date', models.DateField(default=django.utils.timezone.now)),
                ('end_concluded', models.BooleanField(default=False)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_events', to='eventapp.notice')),
            ],
            options={
                'ordering': ['notice_event_type'],
            },
        ),
        migrations.CreateModel(
            name='NoticeEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('default_deadline', models.PositiveIntegerField(blank=True, null=True)),
                ('default_deadline_working_days', models.BooleanField(default=False)),
                ('default_end_concluded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('concluded', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
                ('survey_event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_events', to='eventapp.surveyeventtype')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnd_theme', models.CharField(default='https://bootswatch.com/4/minty/bootstrap.min.css', max_length=255)),
                ('habitese_color', models.CharField(default='#ccffcc', max_length=255)),
                ('reforma_color', models.CharField(default='#99ff99', max_length=255)),
                ('demolicao_color', models.CharField(default='#66ff66', max_length=255)),
                ('renovacao_color', models.CharField(default='#33cc33', max_length=255)),
                ('notice_intimacao_color', models.CharField(default='#3399ff', max_length=255)),
                ('notice_infracao_color', models.CharField(default='#0066ff', max_length=255)),
                ('notice_embargo_color', models.CharField(default='#0000ff', max_length=255)),
                ('notice_intimacao_infracao_color', models.CharField(default='#ff9900', max_length=255)),
                ('notice_intimacao_embargo_color', models.CharField(default='#cc6600', max_length=255)),
                ('notice_infracao_embargo_color', models.CharField(default='#ff3300', max_length=255)),
                ('notice_intimacao_infracao_embargo_color', models.CharField(default='#ff0000', max_length=255)),
                ('notice_deadline_intimacao_color', models.CharField(default='#33ccff', max_length=255)),
                ('notice_deadline_infracao_color', models.CharField(default='#0099ff', max_length=255)),
                ('notice_deadline_vistoria_administrativa_color', models.CharField(default='#0033cc', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notice_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_fines', to='eventapp.noticeevent')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='noticeevent',
            name='notice_event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_events', to='eventapp.noticeeventtype'),
        ),
    ]
