# Generated by Django 3.1.2 on 2020-10-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20201002_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='denuncia_cidadao_color',
            field=models.CharField(default='#46d2a4', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='denuncia_mp_color',
            field=models.CharField(default='#3dbf0d', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='empresa_color',
            field=models.CharField(default='#2f6e0d', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='obras_color',
            field=models.CharField(default='#7eca0c', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cnd_theme',
            field=models.CharField(default='https://bootswatch.com/4/flatly/bootstrap.min.css', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='demolicao_color',
            field=models.CharField(default='#46d2a4', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='habitese_color',
            field=models.CharField(default='#2f6e0d', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_deadline_infracao_color',
            field=models.CharField(default='#f1625b', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_deadline_intimacao_color',
            field=models.CharField(default='#9acada', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_deadline_vistoria_administrativa_color',
            field=models.CharField(default='#7f5b39', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_embargo_color',
            field=models.CharField(default='#f3ec1b', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_infracao_color',
            field=models.CharField(default='#ca1b07', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_infracao_embargo_color',
            field=models.CharField(default='#ff7b00', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_intimacao_color',
            field=models.CharField(default='#2675c5', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_intimacao_embargo_color',
            field=models.CharField(default='#d1cb15', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_intimacao_infracao_color',
            field=models.CharField(default='#d4200c', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notice_intimacao_infracao_embargo_color',
            field=models.CharField(default='#bb1616', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reforma_color',
            field=models.CharField(default='#3dbf0d', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='renovacao_color',
            field=models.CharField(default='#7eca0c', max_length=255),
        ),
    ]
