# Generated by Django 3.1.3 on 2020-11-27 01:55

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_auto_20201126_2109'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension()
    ]
