# Generated by Django 3.1.3 on 2020-12-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_auto_20201126_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis', to='eventapp.lote'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='eventapp.imovel'),
        ),
        migrations.AlterField(
            model_name='surveyevent',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_events', to='eventapp.imovel'),
        ),
    ]
