# Generated by Django 3.1.3 on 2020-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_auto_20201217_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='lote',
        ),
        migrations.AddField(
            model_name='imovel',
            name='CEP',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_lote',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='logradouro',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(default='S/N', max_length=255),
        ),
        migrations.AddField(
            model_name='notice',
            name='document',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveyevent',
            name='document',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
