# Generated by Django 3.1.3 on 2020-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_auto_20201217_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='logradouro',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
