# Generated by Django 3.1.3 on 2020-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_auto_20201217_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='codigo_lote',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
