# Generated by Django 3.1.3 on 2020-12-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0012_auto_20201217_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, default='S/N', max_length=255, null=True),
        ),
    ]
