# Generated by Django 3.1.3 on 2020-12-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0013_auto_20201217_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='CEP',
            new_name='cep',
        ),
    ]
