# Generated by Django 3.1.3 on 2021-01-07 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0014_auto_20201218_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovelupdatelog',
            name='datetime_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
