# Generated by Django 3.1.3 on 2021-04-05 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapp', '0016_auto_20210109_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('css_color', models.CharField(max_length=10, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('identification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('concluded', models.BooleanField(default=False)),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_events', to='eventapp.imovel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('report_event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_events', to='eventapp.reporteventtype')),
            ],
            options={
                'ordering': ['date', 'report_event_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NoticeAppeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('extension', models.PositiveIntegerField(default=0)),
                ('notice_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_appeals', to='eventapp.noticeevent')),
            ],
            options={
                'ordering': ['notice_event', 'start_date', 'id'],
            },
        ),
    ]
