# Generated by Django 3.1.3 on 2021-04-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0017_noticeappeal_reportevent_reporteventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeeventtype',
            name='show_appeal',
            field=models.BooleanField(default=False),
        ),
    ]
