# Generated by Django 3.1.3 on 2021-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0018_noticeeventtype_show_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeappeal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
