# Generated by Django 3.1.3 on 2021-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0019_auto_20210406_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['codigo', 'id']},
        ),
        migrations.CreateModel(
            name='NoticeEventTypeFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file_doc', models.FileField(upload_to='notices/')),
                ('notice_event_types', models.ManyToManyField(to='eventapp.NoticeEventType')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
