# Generated by Django 3.1.3 on 2021-04-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0020_auto_20210407_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeEventTypeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file_doc', models.FileField(upload_to='notices/')),
                ('notice_event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_files', to='eventapp.noticeeventtype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='NoticeEventTypeFiles',
        ),
    ]
