# Generated by Django 3.1.3 on 2021-12-01 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapp', '0024_auto_20211201_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assistentes',
            field=models.ManyToManyField(blank=True, null=True, related_name='auditores', to=settings.AUTH_USER_MODEL),
        ),
    ]
