# Generated by Django 3.1.3 on 2023-03-05 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventapp', '0025_auto_20211201_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelupdatelog',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imovelupdatelog',
            name='datetime_started',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='assistentes',
            field=models.ManyToManyField(blank=True, related_name='auditores', to=settings.AUTH_USER_MODEL),
        ),
    ]
