# Generated by Django 3.1.3 on 2023-03-12 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0028_auto_20230305_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='fracao_ideal',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='zona',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='zona2012',
        ),
        migrations.AddField(
            model_name='imovel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='imported',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
